from flaskblog import create_app

app = create_app()

if __name__ == "__main__":
    # Load SSL certificate paths generated by mkcert
    cert_path = "certs/cert.pem"
    key_path = "certs/key.pem"

    # Run Flask with HTTPS enabled
    app.run(
        host="localhost",
        port=5000,
        ssl_context=(cert_path, key_path)
    )